services:
  nest-app:
    build:
      context: ./
      dockerfile: ./Dockerfile
    depends_on:
      - redis-container
      - mysql-container
    ports:
      - 3001:3001
    # networks:
    #   - common-network
  mysql-container:
    container_name: meet_room_mysql
    image: mysql
    restart: always
    ports:
      - 3306:3306
    volumes:
      - mysql_data:/var/lib/meet-room-mysql/data
    environment:
      MYSQL_ROOT_PASSWORD: 123456
    # network_mode:
    # - "common-network"
    # networks:
    # - common-network
  redis-container:
    container_name: meet_room_redis
    image: redis
    restart: always
    ports:
      - 6379:6379
    volumes:
      - redis_data:/var/lib/redis/data
    # networks:
    # - common-network
    # network_mode:
    # - "common-network"

# docker-compose up -d redis
# docker-compose up -d app

volumes:
  redis_data:
  mysql_data:


# version: '3.8'
# services:
#   nest-app:
#     build:
#       context: ./
#       dockerfile: ./Dockerfile
#     depends_on:
#       - mysql-container
#       - redis-container
#     ports:
#       - 3005:3005
#     networks:
#       - common-network
#   mysql-container:
#     container_name: meet-room-mysql
#     image: mysql
#     restart: always
#     environment:
#     - MYSQL_ROOT_PASSWORD=123456
#     volumes:
#     - mysql_data:/var/lib/meet-room-mysql/data
#     networks:
#     - common-network
#     ports:
#     - 3306:3306
#     env_file:
#     - .env
#   redis-container:
#     container_name: meet-room-redis
#     image: redis
#     restart: always
#     volumes:
#     - redis_data:/var/lib/redis/data
#     networks:
#     - common-network
#     ports:
#       - 6379:6379
#     env_file:
#     - .env
# networks:
#   common-network:
#     driver: bridge

# volumes:
#   redis_data:
#   mysql_data:


# version: '3.8'
# services:
#   nest-app:
#     build:
#       context: ./
#       dockerfile: ./Dockerfile
#     depends_on:
#       - mysql-container
#       - redis-container
#     ports:
#       - 3005:3005
#     networks:
#       - common-network
#   mysql-container:
#     image: mysql
#     volumes:
#       - mysql_data:/var/lib/meet-room-mysql/data
#     environment:
#       MYSQL_DATABASE: meeting_room_booking_system
#       MYSQL_ROOT_PASSWORD: 123456
#     networks:
#       - common-network
#   redis-container:
#     image: redis
#     volumes:
#       - redis_data:/var/lib/redis/data
#     networks:
#       - common-network
# networks:
#   common-network:
#     driver: bridge

# volumes:
#   redis_data:
#   mysql_data:
