# services:
#   nest-app:
#     build:
#       context: ./
#       dockerfile: ./Dockerfile
#     depends_on:
#       - mysql-meet-room
#       - redis-meet-room
#     ports:
#       - '3000:3000'
#   mysql-meet-room:
#     image: mysql
#     restart: always
#     ports:
#       - '3306:3306'
#     volumes:
#       - /Users/meet-room/mysql-data:/var/lib/mysql
#   redis-meet-room:
#     image: redis
#     restart: always
#     ports:
#       - '6379:6379'
#     volumes:
#       - /Users/meet-room/redis_data:/data


version: '3.8'
services:
  nest-app:
    build:
      context: ./
      dockerfile: ./Dockerfile
    depends_on:
      - mysql-container
      - redis-container
    ports:
      - 3005:3005
    networks:
      - common-network
  mysql-container:
    container_name: meet-room-mysql
    image: mysql
    restart: always
    environment:
    - MYSQL_ROOT_PASSWORD=123456
    volumes:
    - mysql_data:/var/lib/meet-room-mysql/data
    networks:
    - common-network
    env_file:
    - .env
  redis-container:
    container_name: meet-room-redis
    image: redis
    restart: always
    volumes:
    - redis_data:/var/lib/redis/data
    networks:
    - common-network
    env_file:
    - .env
networks:
  common-network:
    driver: bridge

volumes:
  redis_data:
  mysql_data:


