version: '3.8'
services:
  # fe-app:
  #   image: registry.cn-hangzhou.aliyuncs.com/ivy-rong/meet-room:bbb
  #   ports:
  #     - 5173:5173
  #   depends_on:
  #     - nest-app
  #   networks:
  #     - meet_room_server_common-network
  #   restart: always
  nest-app:
    build:
      context: ./
      dockerfile: ./Dockerfile
    depends_on:
      - redis-container
      - mysql-container
    ports:
      - 3005:3005
    networks:
      - meet_room_server_common-network
    restart: always
  mysql-container:
    container_name: meet_room_mysql
    image: mysql
    restart: always
    ports:
      - 3306:3306
    volumes:
      - mysql_data:/var/lib/meet-room-mysql/data
    environment:
      MYSQL_DATABASE: meeting_room_booking_system
      MYSQL_ROOT_PASSWORD: 123456
    networks:
      - meet_room_server_common-network
  redis-container:
    container_name: meet_room_redis
    image: redis
    command: redis-server --protected-mode no
    restart: always
    ports:
    - 6379:6379
    volumes:
    - redis_data:/var/lib/redis/data
    networks:
    - meet_room_server_common-network

networks:
  meet_room_server_common-network:
    driver: bridge

volumes:
  redis_data:
  mysql_data:
