services:
  nest-app:
    build:
      context: ./
      dockerfile: ./Dockerfile
    depends_on:
      - mysql-meet-room
      - redis-meet-room
    ports:
      - '3000:3000'
  mysql-meet-room:
    image: mysql
    restart: always
    ports:
      - '3306:3306'
    volumes:
      - /Users/meet-room/mysql-data:/var/lib/mysql
  redis-meet-room:
    image: redis
    restart: always
    ports:
      - '6379:6379'
    volumes:
      - /Users/meet-room/redis_data:/data
